# Site settings
title: Kenny's Blog

author:
  name: Kenneth McHugh
  email: your-email@domain.com
description: "A website."

# Build settings
remote_theme: jekyll/minima

plugins:
- jekyll-remote-theme
